In [1]:
import pandas as pd
import geopandas as gpd 
import requests 
import json
from datetime import datetime
from io import StringIO
import csv
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from shapely import wkt
from scipy.spatial.distance import cdist

import pandas as pd
import geopandas as gpd 
import requests 
import json
from datetime import datetime
from io import StringIO
import csv
import time
import os
import airqualityandclimateAPI
import statsmodels.api as sm

from statsmodels.stats.outliers_influence \
     import variance_inflation_factor as VIF
from statsmodels.stats.anova import anova_lm

from ISLP import load_data
from ISLP.models import (ModelSpec as MS,
                         summarize,
                         poly)
from linearmodels import PanelOLS

In [2]:
import sklearn.model_selection as skm
import sklearn.linear_model as skl
from sklearn.preprocessing import StandardScaler
from ISLP import load_data
from ISLP.models import (ModelSpec as MS, summarize)
from functools import partial
from sklearn.pipeline import Pipeline
# from sklearn.decomposition import PCA
from sklearn.cross_decomposition import PLSRegression
from ISLP.models import \
     (Stepwise,
      sklearn_selected,
      sklearn_selection_path)

In [10]:
import Analysis
from Analysis import model_4_lasso_panel

In [4]:
import Final_LASSO
import Random_Forest

In [5]:
totaldataframe = Analysis.totaldata()

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:87: DtypeWarning: Columns (8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  totaldf = pd.read_csv(totaldatapath)

# LASSO

#### Final LASSO using PM2.5

In [6]:
finallassopm = Final_LASSO.final_LASSO(totaldataframe, pm=True)

Non-numeric columns remaining: []
NaNs in X: 0
Initiating Shuffle Split:
Fitting Hyper Parameter Pipeline:

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:1622: FutureWarning: 'n_alphas' was deprecated in 1.7 and will be removed in 1.9. 'alphas' now accepts an integer value which removes the need to pass 'n_alphas'. The default value of 'alphas' will change from None to 100 in 1.9. Pass an explicit value to 'alphas' and leave 'n_alphas' to its default value to silence this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.390e+03, tolerance: 1.892e+02
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.126e+02, tolerance: 1.892e+02
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.520e+02, tolerance: 1.892e+02
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.556e+02, tolerance: 1.917e+02
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.987e+02, tolerance: 1.917e+02
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.276e+02, tolerance: 1.917e+02
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.162e+02, tolerance: 1.917e+02
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.465e+02, tolerance: 1.917e+02
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.351e+02, tolerance: 1.917e+02
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.003e+05, tolerance: 2.352e+02
  model = cd_fast.enet_coordinate_descent(

Tuned alpha = 0.01295247137914592
Testing the Tuned Lasso with Cross Validation:
results saved
The non-zero coefficient estimates are:
                                        feature  coefficient
5                DailyMaximumDryBulbTemperature     1.714400
31                        CO2 Mass (short tons)     1.511161
30                        SO2 Mass (short tons)    -1.150008
37                                  sunrise_cos    -1.128472
4    DailyDepartureFromNormalAverageTemperature     1.084164
..                                          ...          ...
98         DailySustainedWindDirection_cos_lag2    -0.001576
108          DailyAverageWindDirection_sin_lag2    -0.001514
65           DailyAverageWindDirection_sin_lag1    -0.000828
96              DailyPeakWindDirection_cos_lag2    -0.000145
161                                   YEAR_lag3    -0.000033

[80 rows x 2 columns]

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.707e+03, tolerance: 2.916e+02
  model = cd_fast.enet_coordinate_descent(

In [13]:
finallassofeaturespm = finallassopm[2]
finallassofeaturespm

['DailyMaximumDryBulbTemperature',
 'CO2 Mass (short tons)',
 'SO2 Mass (short tons)',
 'sunrise_cos',
 'DailyDepartureFromNormalAverageTemperature',
 'Sunrise_lag3',
 'AQlatitude',
 'DailyMinimumDryBulbTemperature_lag3',
 'sunrise_cos_lag1',
 'sunrise_cos_lag2',
 'sunrise_cos_lag3',
 'CO2 Mass (short tons)_lag3',
 'NUM_READS',
 'DailyMinimumDryBulbTemperature',
 'BUS_COUNT',
 'Sunrise',
 'sunset_cos',
 'DailyPeakWindSpeed_lag3',
 'NOx Mass (short tons)_lag3',
 'DailySustainedWindDirection_cos']

#### Final LASSO using AQI

In [14]:
finallassoaqi = Final_LASSO.final_LASSO(totaldataframe, pm=False)
finallassofeaturesaqi = finallassoaqi[2]
finallassofeaturesaqi

Non-numeric columns remaining: []
NaNs in X: 0
Initiating Shuffle Split:
Fitting Hyper Parameter Pipeline:

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:1622: FutureWarning: 'n_alphas' was deprecated in 1.7 and will be removed in 1.9. 'alphas' now accepts an integer value which removes the need to pass 'n_alphas'. The default value of 'alphas' will change from None to 100 in 1.9. Pass an explicit value to 'alphas' and leave 'n_alphas' to its default value to silence this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.530e+03, tolerance: 1.387e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.154e+03, tolerance: 1.387e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.064e+03, tolerance: 1.387e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.515e+03, tolerance: 1.387e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.262e+03, tolerance: 1.387e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.133e+03, tolerance: 1.369e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.631e+03, tolerance: 1.369e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.619e+03, tolerance: 1.380e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.168e+03, tolerance: 1.380e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.569e+03, tolerance: 1.380e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.698e+03, tolerance: 1.380e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.436e+03, tolerance: 1.380e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.713e+03, tolerance: 1.391e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.279e+03, tolerance: 1.391e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.621e+03, tolerance: 1.391e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.693e+03, tolerance: 1.391e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.302e+03, tolerance: 1.391e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.968e+03, tolerance: 1.380e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.800e+03, tolerance: 1.380e+03
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.069e+05, tolerance: 1.727e+03
  model = cd_fast.enet_coordinate_descent(

Tuned alpha = 0.050032627590710296
Testing the Tuned Lasso with Cross Validation:
results saved
The non-zero coefficient estimates are:
                                        feature  coefficient
5                DailyMaximumDryBulbTemperature     6.821557
4    DailyDepartureFromNormalAverageTemperature     4.129789
132         DailyMinimumDryBulbTemperature_lag3    -4.015636
31                        CO2 Mass (short tons)     3.987862
27                                   AQlatitude    -3.778697
..                                          ...          ...
96              DailyPeakWindDirection_cos_lag2    -0.005598
36                                  sunrise_sin    -0.005139
95              DailyPeakWindDirection_sin_lag2     0.003593
48                      DailyPrecipitation_lag1     0.002908
16                 DailyAverageAltimeterSetting     0.002848

[65 rows x 2 columns]

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.236e+04, tolerance: 2.166e+03
  model = cd_fast.enet_coordinate_descent(

['DailyMaximumDryBulbTemperature',
 'DailyDepartureFromNormalAverageTemperature',
 'DailyMinimumDryBulbTemperature_lag3',
 'CO2 Mass (short tons)',
 'AQlatitude',
 'DailyMinimumDryBulbTemperature',
 'sunrise_cos',
 'sunset_cos_lag3',
 'NUM_READS',
 'SO2 Mass (short tons)',
 'BUS_COUNT',
 'sunrise_cos_lag1',
 'DailySustainedWindDirection_cos',
 'DailyPeakWindSpeed_lag3',
 'sunset_cos',
 'sunrise_cos_lag2',
 'AQlongitude',
 'CO2 Mass (short tons)_lag3',
 'DailyPeakWindSpeed',
 'DailyPeakWindDirection_sin']

In [16]:
xmatrixpm = finallassofeaturespm
xmatrixaqi = finallassofeaturesaqi

fe = ['CLIMATE_STATION_NAME','YEAR']
fe2 = ['CLIMATE_STATION_NAME','YEAR','AQ_STATION_NAME']

y = ['arithmetic_mean']

# xvars = ['Number', 'Capacity']
xvarsnum = ['Number']
xvarscap = ['Capacity']

## X variables using the PM results: 
x_pm_num = xvarsnum + xmatrixpm
x_pm_cap = xvarscap + xmatrixpm

## X variables using the AQIQ results:
x_aqi_num = xvarsnum + xmatrixaqi
x_aqi_cap = xvarscap + xmatrixaqi

# totalcols = x+y

OLS LASSO PM using Number of gens:

In [17]:
OLS_PM_NUM = model_4_lasso_panel(totaldataframe, x_pm_num, y, fe)
print(OLS_PM_NUM)

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:780: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

sunrise_cos, sunrise_cos_lag1, sunrise_cos_lag2, sunset_cos

  results = model.fit(cov_type='clustered', cluster_entity=True)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:        arithmetic_mean   R-squared:                        0.1407
Estimator:                   PanelOLS   R-squared (Between):             -0.9453
No. Observations:               72978   R-squared (Within):               0.1431
Date:                Wed, Apr 08 2026   R-squared (Overall):              0.1421
Time:                        14:08:31   Log-likelihood                -2.316e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      746.35
Entities:                           2   P-value                           0.0000
Avg Obs:                    3.649e+04   Distribution:                F(16,72951)
Min Obs:                    3.575e+04
Max Obs:                    3.723e+04   F-statistic (robust):          1.508e+16
                                        P-value                           0.0000
Time periods:                      10   Distribution:                F(16,72951)
Avg Obs:                       7297.8
Min Obs:                       96.000
Max Obs:                    1.184e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
Number                                        -0.0010     0.0001    -8.2346     0.0000     -0.0012     -0.0007
DailyMaximumDryBulbTemperature                 0.1270     0.0273     4.6553     0.0000      0.0735      0.1804
CO2 Mass (short tons)                       2.968e-05  9.621e-07     30.851     0.0000    2.78e-05   3.157e-05
SO2 Mass (short tons)                         -0.0155     0.0003    -50.984     0.0000     -0.0161     -0.0149
DailyDepartureFromNormalAverageTemperature     0.2947     0.0343     8.5892     0.0000      0.2274      0.3619
Sunrise_lag3                                   0.0072     0.0185     0.3908     0.6960     -0.0290      0.0435
AQlatitude                                    -3.7363     2.2652    -1.6495     0.0991     -8.1761      0.7034
DailyMinimumDryBulbTemperature_lag3           -0.0113     0.0476    -0.2366     0.8130     -0.1046      0.0821
sunrise_cos_lag3                               166.28     93.728     1.7740     0.0761     -17.430      349.98
CO2 Mass (short tons)_lag3                  2.548e-05  5.623e-06     4.5321     0.0000   1.446e-05    3.65e-05
NUM_READS                                      0.0039     0.0009     4.3622     0.0000      0.0022      0.0057
DailyMinimumDryBulbTemperature                -0.1886     0.0578    -3.2630     0.0011     -0.3018     -0.0753
BUS_COUNT                                     -0.0888     0.0239    -3.7160     0.0002     -0.1356     -0.0419
Sunrise                                       -0.0087     0.0202    -0.4308     0.6666     -0.0482      0.0309
DailyPeakWindSpeed_lag3                       -0.2655     0.0110    -24.049     0.0000     -0.2872     -0.2439
NOx Mass (short tons)_lag3                    -0.0491     0.0093    -5.3086     0.0000     -0.0673     -0.0310
DailySustainedWindDirection_cos               -1.3135     0.0271    -48.397     0.0000     -1.3667     -1.2603
==============================================================================================================

F-test for Poolability: 156.95
P-value: 0.0000
Distribution: F(10,72951)

Included effects: Entity, Time

OLS LASSO PM using Daily sum of added gen capacity

In [18]:
OLS_PM_CAP = model_4_lasso_panel(totaldataframe, x_pm_cap, y , fe)
print(OLS_PM_CAP)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:        arithmetic_mean   R-squared:                        0.1407
Estimator:                   PanelOLS   R-squared (Between):             -0.9478
No. Observations:               72978   R-squared (Within):               0.1432
Date:                Wed, Apr 08 2026   R-squared (Overall):              0.1422
Time:                        14:09:05   Log-likelihood                -2.316e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      746.57
Entities:                           2   P-value                           0.0000
Avg Obs:                    3.649e+04   Distribution:                F(16,72951)
Min Obs:                    3.575e+04
Max Obs:                    3.723e+04   F-statistic (robust):         -2.878e+17
                                        P-value                           1.0000
Time periods:                      10   Distribution:                F(16,72951)
Avg Obs:                       7297.8
Min Obs:                       96.000
Max Obs:                    1.184e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
Capacity                                      -0.0970     0.0044    -22.075     0.0000     -0.1056     -0.0884
DailyMaximumDryBulbTemperature                 0.1271     0.0272     4.6710     0.0000      0.0737      0.1804
CO2 Mass (short tons)                       2.966e-05  9.553e-07     31.046     0.0000   2.779e-05   3.153e-05
SO2 Mass (short tons)                         -0.0155     0.0003    -50.888     0.0000     -0.0161     -0.0149
DailyDepartureFromNormalAverageTemperature     0.2944     0.0343     8.5890     0.0000      0.2272      0.3615
Sunrise_lag3                                   0.0072     0.0185     0.3877     0.6982     -0.0291      0.0435
AQlatitude                                    -3.7377     2.2634    -1.6514     0.0987     -8.1740      0.6986
DailyMinimumDryBulbTemperature_lag3           -0.0111     0.0476    -0.2345     0.8146     -0.1044      0.0821
sunrise_cos_lag3                               166.33     93.655     1.7759     0.0757     -17.237      349.89
CO2 Mass (short tons)_lag3                   2.55e-05  5.631e-06     4.5286     0.0000   1.446e-05   3.654e-05
NUM_READS                                      0.0040     0.0009     4.3924     0.0000      0.0022      0.0057
DailyMinimumDryBulbTemperature                -0.1886     0.0577    -3.2675     0.0011     -0.3017     -0.0755
BUS_COUNT                                     -0.0890     0.0238    -3.7430     0.0002     -0.1357     -0.0424
Sunrise                                       -0.0086     0.0202    -0.4273     0.6691     -0.0482      0.0310
DailyPeakWindSpeed_lag3                       -0.2655     0.0111    -23.947     0.0000     -0.2872     -0.2438
NOx Mass (short tons)_lag3                    -0.0491     0.0093    -5.2894     0.0000     -0.0673     -0.0309
DailySustainedWindDirection_cos               -1.3122     0.0276    -47.599     0.0000     -1.3662     -1.2582
==============================================================================================================

F-test for Poolability: 156.08
P-value: 0.0000
Distribution: F(10,72951)

Included effects: Entity, Time

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:780: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

sunrise_cos, sunrise_cos_lag1, sunrise_cos_lag2, sunset_cos

  results = model.fit(cov_type='clustered', cluster_entity=True)

OLS AQI using Number:

In [19]:
OLS_AQI_NUM = model_4_lasso_panel(totaldataframe, x_aqi_num, y, fe)
print(OLS_AQI_NUM)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:        arithmetic_mean   R-squared:                        0.1464
Estimator:                   PanelOLS   R-squared (Between):             -0.7487
No. Observations:               72978   R-squared (Within):               0.1476
Date:                Wed, Apr 08 2026   R-squared (Overall):              0.1468
Time:                        14:25:51   Log-likelihood                -2.313e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      782.18
Entities:                           2   P-value                           0.0000
Avg Obs:                    3.649e+04   Distribution:                F(16,72951)
Min Obs:                    3.575e+04
Max Obs:                    3.723e+04   F-statistic (robust):          1.293e+18
                                        P-value                           0.0000
Time periods:                      10   Distribution:                F(16,72951)
Avg Obs:                       7297.8
Min Obs:                       96.000
Max Obs:                    1.184e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
Number                                        -0.0011  2.312e-05    -48.681     0.0000     -0.0012     -0.0011
DailyMaximumDryBulbTemperature                 0.1518     0.0148     10.272     0.0000      0.1228      0.1808
DailyDepartureFromNormalAverageTemperature     0.2729     0.0261     10.471     0.0000      0.2218      0.3239
DailyMinimumDryBulbTemperature_lag3           -0.0772     0.0298    -2.5955     0.0094     -0.1356     -0.0189
CO2 Mass (short tons)                       2.907e-05  1.433e-07     202.95     0.0000   2.879e-05   2.935e-05
AQlatitude                                    -5.6201     1.7358    -3.2377     0.0012     -9.0223     -2.2178
DailyMinimumDryBulbTemperature                -0.1252     0.0326    -3.8399     0.0001     -0.1891     -0.0613
NUM_READS                                      0.0048     0.0008     5.7036     0.0000      0.0031      0.0064
SO2 Mass (short tons)                         -0.0204     0.0014    -14.945     0.0000     -0.0231     -0.0178
BUS_COUNT                                     -0.1008     0.0232    -4.3488     0.0000     -0.1462     -0.0554
DailySustainedWindDirection_cos               -1.2714     0.0314    -40.505     0.0000     -1.3329     -1.2099
DailyPeakWindSpeed_lag3                       -0.1077     0.0073    -14.704     0.0000     -0.1221     -0.0934
sunrise_cos_lag2                              -150.28     73.476    -2.0453     0.0408     -294.29     -6.2674
AQlongitude                                   -4.4875     1.6647    -2.6957     0.0070     -7.7503     -1.2248
CO2 Mass (short tons)_lag3                  8.698e-06  1.601e-06     5.4335     0.0000    5.56e-06   1.184e-05
DailyPeakWindSpeed                            -0.1508     0.0067    -22.382     0.0000     -0.1641     -0.1376
DailyPeakWindDirection_sin                     0.5232     0.1522     3.4367     0.0006      0.2248      0.8216
==============================================================================================================

F-test for Poolability: 165.43
P-value: 0.0000
Distribution: F(10,72951)

Included effects: Entity, Time

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:780: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

sunrise_cos, sunset_cos_lag3, sunrise_cos_lag1, sunset_cos

  results = model.fit(cov_type='clustered', cluster_entity=True)

OLS AQI using Capacity:

In [20]:
OLS_AQI_CAP = model_4_lasso_panel(totaldataframe, x_aqi_cap, y, fe)
print(OLS_AQI_CAP)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:        arithmetic_mean   R-squared:                        0.1465
Estimator:                   PanelOLS   R-squared (Between):             -0.7495
No. Observations:               72978   R-squared (Within):               0.1477
Date:                Wed, Apr 08 2026   R-squared (Overall):              0.1469
Time:                        14:25:55   Log-likelihood                -2.313e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      782.38
Entities:                           2   P-value                           0.0000
Avg Obs:                    3.649e+04   Distribution:                F(16,72951)
Min Obs:                    3.575e+04
Max Obs:                    3.723e+04   F-statistic (robust):          1.568e+17
                                        P-value                           0.0000
Time periods:                      10   Distribution:                F(16,72951)
Avg Obs:                       7297.8
Min Obs:                       96.000
Max Obs:                    1.184e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
Capacity                                      -0.1064     0.0121    -8.8040     0.0000     -0.1301     -0.0827
DailyMaximumDryBulbTemperature                 0.1518     0.0148     10.284     0.0000      0.1228      0.1807
DailyDepartureFromNormalAverageTemperature     0.2727     0.0261     10.463     0.0000      0.2216      0.3238
DailyMinimumDryBulbTemperature_lag3           -0.0771     0.0297    -2.5976     0.0094     -0.1352     -0.0189
CO2 Mass (short tons)                       2.906e-05  1.343e-07     216.40     0.0000   2.879e-05   2.932e-05
AQlatitude                                    -5.6205     1.7341    -3.2412     0.0012     -9.0192     -2.2217
DailyMinimumDryBulbTemperature                -0.1253     0.0325    -3.8540     0.0001     -0.1890     -0.0616
NUM_READS                                      0.0048     0.0008     5.7431     0.0000      0.0031      0.0064
SO2 Mass (short tons)                         -0.0204     0.0014    -14.863     0.0000     -0.0231     -0.0177
BUS_COUNT                                     -0.1011     0.0231    -4.3815     0.0000     -0.1463     -0.0559
DailySustainedWindDirection_cos               -1.2701     0.0318    -39.999     0.0000     -1.3324     -1.2079
DailyPeakWindSpeed_lag3                       -0.1078     0.0074    -14.578     0.0000     -0.1222     -0.0933
sunrise_cos_lag2                              -150.14     73.503    -2.0427     0.0411     -294.21     -6.0761
AQlongitude                                   -4.4862     1.6641    -2.6958     0.0070     -7.7478     -1.2245
CO2 Mass (short tons)_lag3                  8.713e-06  1.594e-06     5.4662     0.0000   5.589e-06   1.184e-05
DailyPeakWindSpeed                            -0.1507     0.0068    -22.232     0.0000     -0.1640     -0.1375
DailyPeakWindDirection_sin                     0.5233     0.1523     3.4371     0.0006      0.2249      0.8217
==============================================================================================================

F-test for Poolability: 164.45
P-value: 0.0000
Distribution: F(10,72951)

Included effects: Entity, Time

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:780: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

sunrise_cos, sunset_cos_lag3, sunrise_cos_lag1, sunset_cos

  results = model.fit(cov_type='clustered', cluster_entity=True)

Random Forest using PM:

In [21]:
random_forest_pm = Random_Forest.random_forest(totaldataframe, pm=True)

Number of NaNs in X: 0
Preprocessing setup complete.
Fitting the Grid Search for RF hyperparameter tuning...
100
Fitting the RF model
(51082, 168)
                                             feature  importance
112                       SO2 Mass (short tons)_lag2    0.014460
139                  DailyPeakWindDirection_cos_lag3    0.013461
4         DailyDepartureFromNormalAverageTemperature    0.013183
80                                         DATE_lag2    0.012534
130  DailyDepartureFromNormalAverageTemperature_lag3    0.011551
114                       NOx Mass (short tons)_lag2    0.011299
156                       CO2 Mass (short tons)_lag3    0.010971
98              DailySustainedWindDirection_cos_lag2    0.010831
36                                       sunrise_sin    0.010700
10                                           Sunrise    0.010583
29                                  Gross Load (MWh)    0.010549
44   DailyDepartureFromNormalAverageTemperature_lag1    0.010475
0                                               DATE    0.010391
31                             CO2 Mass (short tons)    0.010364
79                                   sunset_cos_lag1    0.010275
76                                  sunrise_sin_lag1    0.010270
13                        DailyPeakWindDirection_cos    0.010186
40                                         DATE_lag1    0.010163
71                        NOx Mass (short tons)_lag1    0.010126
123                                        DATE_lag3    0.010051
121                                  sunset_sin_lag2    0.009941
53                   DailyPeakWindDirection_cos_lag1    0.009771
92                      DailySustainedWindSpeed_lag2    0.009570
87   DailyDepartureFromNormalAverageTemperature_lag2    0.009359
7                                 DailyPeakWindSpeed    0.009194
141             DailySustainedWindDirection_cos_lag3    0.009190
38                                        sunset_sin    0.009029
155                       SO2 Mass (short tons)_lag3    0.008925
6                     DailyMinimumDryBulbTemperature    0.008797
35                                             SPEED    0.008768
55              DailySustainedWindDirection_cos_lag1    0.008745
45               DailyMaximumDryBulbTemperature_lag1    0.008719
30                             SO2 Mass (short tons)    0.008603
111                            Gross Load (MWh)_lag2    0.008581
157                       NOx Mass (short tons)_lag3    0.008552
136                                     Sunrise_lag3    0.008485
164                                  sunset_sin_lag3    0.008444
49                      DailySustainedWindSpeed_lag1    0.008374
46               DailyMinimumDryBulbTemperature_lag1    0.008321
113                       CO2 Mass (short tons)_lag2    0.008245
-4.822464383781256
[12.62601998  6.90541578 11.29304703 ...  9.58808696  7.09935394
 10.91914419]

In [25]:
random_forest_pm[3].head(20)

                                             feature  importance
112                       SO2 Mass (short tons)_lag2    0.014460
139                  DailyPeakWindDirection_cos_lag3    0.013461
4         DailyDepartureFromNormalAverageTemperature    0.013183
80                                         DATE_lag2    0.012534
130  DailyDepartureFromNormalAverageTemperature_lag3    0.011551
114                       NOx Mass (short tons)_lag2    0.011299
156                       CO2 Mass (short tons)_lag3    0.010971
98              DailySustainedWindDirection_cos_lag2    0.010831
36                                       sunrise_sin    0.010700
10                                           Sunrise    0.010583
29                                  Gross Load (MWh)    0.010549
44   DailyDepartureFromNormalAverageTemperature_lag1    0.010475
0                                               DATE    0.010391
31                             CO2 Mass (short tons)    0.010364
79                                   sunset_cos_lag1    0.010275
76                                  sunrise_sin_lag1    0.010270
13                        DailyPeakWindDirection_cos    0.010186
40                                         DATE_lag1    0.010163
71                        NOx Mass (short tons)_lag1    0.010126
123                                        DATE_lag3    0.010051

Random Forest using AQI:

In [ ]:
random_forest_aqi = Random_Forest.random_forest(totaldataframe, pm=False)

Number of NaNs in X: 0
Preprocessing setup complete.
Fitting the Grid Search for RF hyperparameter tuning...
100
Fitting the RF model
(51082, 168)
                                             feature  importance
4         DailyDepartureFromNormalAverageTemperature    0.016058
44   DailyDepartureFromNormalAverageTemperature_lag1    0.015018
87   DailyDepartureFromNormalAverageTemperature_lag2    0.013881
53                   DailyPeakWindDirection_cos_lag1    0.013785
130  DailyDepartureFromNormalAverageTemperature_lag3    0.013110
98              DailySustainedWindDirection_cos_lag2    0.012847
139                  DailyPeakWindDirection_cos_lag3    0.012210
96                   DailyPeakWindDirection_cos_lag2    0.011879
55              DailySustainedWindDirection_cos_lag1    0.011819
15                   DailySustainedWindDirection_cos    0.011058
141             DailySustainedWindDirection_cos_lag3    0.010765
88               DailyMaximumDryBulbTemperature_lag2    0.010588
80                                         DATE_lag2    0.010227
131              DailyMaximumDryBulbTemperature_lag3    0.010170
5                     DailyMaximumDryBulbTemperature    0.009993
45               DailyMaximumDryBulbTemperature_lag1    0.009658
154                            Gross Load (MWh)_lag3    0.009088
111                            Gross Load (MWh)_lag2    0.009055
69                        SO2 Mass (short tons)_lag1    0.008796
40                                         DATE_lag1    0.008782
7                                 DailyPeakWindSpeed    0.008747
68                             Gross Load (MWh)_lag1    0.008725
123                                        DATE_lag3    0.008672
0                                               DATE    0.008644
92                      DailySustainedWindSpeed_lag2    0.008458
132              DailyMinimumDryBulbTemperature_lag3    0.008424
89               DailyMinimumDryBulbTemperature_lag2    0.008420
117                                       SPEED_lag2    0.008344
114                       NOx Mass (short tons)_lag2    0.008301
49                      DailySustainedWindSpeed_lag1    0.008234
156                       CO2 Mass (short tons)_lag3    0.008156
6                     DailyMinimumDryBulbTemperature    0.008146
112                       SO2 Mass (short tons)_lag2    0.008134
71                        NOx Mass (short tons)_lag1    0.008000
135                     DailySustainedWindSpeed_lag3    0.007962
32                             NOx Mass (short tons)    0.007930
133                          DailyPeakWindSpeed_lag3    0.007848
29                                  Gross Load (MWh)    0.007809
90                           DailyPeakWindSpeed_lag2    0.007804
9                            DailySustainedWindSpeed    0.007794
-41.74736766608948
[55.44163392 35.29683896 54.58824199 ... 49.2802923  34.51589269
 52.71417926]

In [24]:
random_forest_aqi[3].head(20)

                                             feature  importance
4         DailyDepartureFromNormalAverageTemperature    0.016058
44   DailyDepartureFromNormalAverageTemperature_lag1    0.015018
87   DailyDepartureFromNormalAverageTemperature_lag2    0.013881
53                   DailyPeakWindDirection_cos_lag1    0.013785
130  DailyDepartureFromNormalAverageTemperature_lag3    0.013110
98              DailySustainedWindDirection_cos_lag2    0.012847
139                  DailyPeakWindDirection_cos_lag3    0.012210
96                   DailyPeakWindDirection_cos_lag2    0.011879
55              DailySustainedWindDirection_cos_lag1    0.011819
15                   DailySustainedWindDirection_cos    0.011058
141             DailySustainedWindDirection_cos_lag3    0.010765
88               DailyMaximumDryBulbTemperature_lag2    0.010588
80                                         DATE_lag2    0.010227
131              DailyMaximumDryBulbTemperature_lag3    0.010170
5                     DailyMaximumDryBulbTemperature    0.009993
45               DailyMaximumDryBulbTemperature_lag1    0.009658
154                            Gross Load (MWh)_lag3    0.009088
111                            Gross Load (MWh)_lag2    0.009055
69                        SO2 Mass (short tons)_lag1    0.008796
40                                         DATE_lag1    0.008782

# Making Tables

In [26]:
import os
from stargazer.stargazer import Stargazer, LineLocation

In [28]:
Star = Stargazer([OLS_PM_NUM])
Star